// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl_s-QdNjUOYmx1iYUeusOxQW3F2CJaCY',
    appId: '1:115946594164:web:b35dfab317225f44a4d621',
    messagingSenderId: '115946594164',
    projectId: 'archivos-nutricion',
    authDomain: 'archivos-nutricion.firebaseapp.com',
    storageBucket: 'archivos-nutricion.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFG7LRZYna_A6pMPefbGTDsEvEuXEdgJ8',
    appId: '1:115946594164:android:4807744022f71cd4a4d621',
    messagingSenderId: '115946594164',
    projectId: 'archivos-nutricion',
    storageBucket: 'archivos-nutricion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8t6FBBOxnwB_ExNz0aYbiFUX6nmgD4xw',
    appId: '1:115946594164:ios:284c6b73a5f3513ca4d621',
    messagingSenderId: '115946594164',
    projectId: 'archivos-nutricion',
    storageBucket: 'archivos-nutricion.appspot.com',
    iosClientId:
        '115946594164-6q9827781kd42qbfn5ovlr0666m19hlm.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplicacionMovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8t6FBBOxnwB_ExNz0aYbiFUX6nmgD4xw',
    appId: '1:115946594164:ios:284c6b73a5f3513ca4d621',
    messagingSenderId: '115946594164',
    projectId: 'archivos-nutricion',
    storageBucket: 'archivos-nutricion.appspot.com',
    iosClientId:
        '115946594164-6q9827781kd42qbfn5ovlr0666m19hlm.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplicacionMovil',
  );
}
